# -*- coding: utf-8 -*-
"""Calculadora (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IC-gFeGBaXG1f97hjlom-_wP73AfdlBy
"""



# Calduradora

print("Bem-vindo/a à calculadora!\n\n") # Mensagem de início

nome_usuario = input("Por favor, insira seu nome: ") # Identificão do usuário
print(f"\nOlá,{nome_usuario}\n")

numero1=float(input("Insira o primeira número: ")) # Coleta do primeiro número
print(f"\nO primeiro número é: {numero1}\n")

numero2=float(input("Insira o segundo número: ")) # Coleta do segundo número
print(f"\nO segundo número é: {numero2}\n")

operacao = input("Por favor, insira a operação desejada (+, -, /, *) : ") # Identificando a operação desejada pelo usuário

if operacao == "+":
 resultado = numero1+numero2
 print(f"\nO resultado da soma é: {resultado}\n") # Resultado da operação de soma.

elif operacao == "-":
 resultado2 = numero1-numero2
 print(f"\nO resultado de subtração é: {resultado2}\n") # Resultado da operação de subtração.

elif operacao == "/":
 resultado3 = numero1/numero2
 print(f"\nO resultado da divisão é: {resultado3}\n") # Resultado da operação de divisão.

elif operacao == "*":
 resultado4 = numero1*numero2
 print(f"\nO resultado da multiplicação é: {resultado4}\n") # Resultado da operação de multiplicação.

print(f"\nObrigado/a por utilizar a calculadora!") # Encerramento da calculadora